acme_board:
    resource: "@AcmeBoardBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/board
    defaults: { _locale: en }
    requirements:
        culture:  _locale: en

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        culture:  _locale: en|zh

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
  
acme_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'AcmeBoardBundle:Static:privacy.html.twig'
        maxAge:       86400
        sharedAge:    86400
  
acme_homepage:
    pattern:  /{_locale}
    defaults: { _controller: AcmeBoardBundle:Default:index, _locale: en }

