acme_board:
    resource: "@AcmeBoardBundle/Resources/config/routing.yml"
    prefix:   /board

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults: { _locale: en }
    requirements:
        culture:  _locale: en|zh

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
acme_homepage:
    pattern:  /
    defaults: { _controller: AcmeBoardBundle:Default:index }
