_user_secured:
    resource: "secured.yml"
    prefix:   /secured

message:
    resource: "message.yml"
    prefix:   /user    

board:
    resource: "board.yml"
    prefix:   /user

settings:
    resource: "settings.yml"
    prefix:   /settings

user_exp:
    pattern:  /user/exp
    defaults: { _controller: AcmeUserBundle:Message:exp }
    options:
        expose: true

locale:
    pattern:  /locale
    defaults: { _controller: AcmeUserBundle:Locale:change }

resetting:
    resource: "resetting.yml"
    prefix:   /resetting

