acme_board_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeBoardBundle:Default:index }

thread_index:
    pattern: /{module_id}
    defaults: { _controller: AcmeBoardBundle:Thread:index, module_id: 1 }
    requirements:
        module_id:  \d+
    options:
        expose: true

#category_index:    

thread_view:
    pattern: /thread/{id}
    defaults: { _controller: AcmeBoardBundle:Thread:view } 
    requirements:
        id:  \d+
 
thread_create:
    pattern: /thread/create
    defaults: { _controller: AcmeBoardBundle:Thread:create }

comment_create:
    pattern: /comment/create
    defaults: { _controller: AcmeBoardBundle:Comment:create }

search:
    pattern: /search
    defaults: { _controller: AcmeBoardBundle:Search:index }

index:
    pattern: /module
    defaults: { _controller: AcmeBoardBundle:Module:index }
