thread_index:
    pattern: /{module_id}
    defaults: { _controller: AcmeBoardBundle:Thread:index }
    requirements:
        module_id:  \d+

thread_view:
    pattern: /thread/{id}
    defaults: { _controller: AcmeBoardBundle:Thread:view } 
    requirements:
        id:  \d+
 
thread_create:
    pattern: /thread/create
    defaults: { _controller: AcmeBoardBundle:Thread:create }

comment_create:
    pattern: /comment/create
    defaults: { _controller: AcmeBoardBundle:Comment:create }

search:
    pattern: /search
    defaults: { _controller: AcmeBoardBundle:Search:index }

module_index:
    pattern: /
    defaults: { _controller: AcmeBoardBundle:Module:index }

rate_increase:
    pattern: /rate/increase
    defaults: { _controller: AcmeBoardBundle:Rate:increase }
    options:
        expose: true
