thread_index:
    pattern: /{module_id}
    defaults: { _controller: AcmeBoardBundle:Thread:index }
    requirements:
        module_id:  \d+

thread_view:
    pattern: /thread/{id}
    defaults: { _controller: AcmeBoardBundle:Thread:view } 
    requirements:
        id:  \d+
 
thread_create:
    pattern: /thread/create
    defaults: { _controller: AcmeBoardBundle:Thread:create }
    
thread_edit:
    pattern: /thread/edit/{id}
    defaults: { _controller: AcmeBoardBundle:Thread:edit }
    requirements:
        id:  \d+    

comment_create:
    pattern: /comment/create
    defaults: { _controller: AcmeBoardBundle:Comment:create }

#search:
#    pattern: /search
#    defaults: { _controller: AcmeBoardBundle:Search:index }

module_index:
    pattern: /
    defaults: { _controller: AcmeBoardBundle:Module:index }

comment_vote:
    pattern: /comment/vote
    defaults: { _controller: AcmeBoardBundle:Asynchrony:vote }
    options:
        expose: true
    methods:  [POST]        
        
comment_check:
    pattern: /comment/check
    defaults: { _controller: AcmeBoardBundle:Comment:check }
    options:
        expose: true
