# Acme/BoardBundle/Resources/config/validation.yml
Acme\BoardBundle\Entity\Thread:
    properties:
        title:
            - NotBlank: ~        
            - Length:
                min: 4
                max: 128
        content:
            - NotBlank: ~        
            - Length:
                min: 10
                max: 1024

Acme\BoardBundle\Entity\Comment:
    properties:
        content:
            - NotBlank: ~        
            - Length:
                min: 10
                max: 1024               
            
