<?php

namespace Acme\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acme\UserBundle\Entity\User;

/**
 * CommentTrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentTrackRepository extends EntityRepository
{
    
    public function create(User $user, Comment $comment)
    {
        $track = new \Acme\BoardBundle\Entity\CommentTrack();
        $track->setUser($user)
            ->setComment($comment)
            ->setThread($comment->getThread())
            ->setHasVoted(true);
              
        $comment->setVotes($comment->getVotes() + 1);
        $this->_em->persist($track);               
        $this->_em->persist($comment);        
        $this->_em->flush();
    }
    
    public function findByUserAndThread(User $user = null, Thread $thread)
    {
        $tracks = array();
        
        if (!isset($user)) {
            return $tracks;
        }
        
        $dql = "SELECT ct FROM AcmeBoardBundle:CommentTrack ct
            WHERE ct.user = :user AND ct.thread = :thread";
        $query = $this->_em->createQuery($dql)
            ->setParameter('user', $user->getId())
            ->setParameter('thread', $thread->getId());  
        $tracks = $query->getResult();
                
        return $tracks;
    }
}
