<?php

namespace Acme\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findById($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT m FROM AcmeBoardBundle:Module m 
            WHERE m.id = :module_id')
            ->setParameter('module_id', $id);
            
        return $query->getSingleResult();
        /*   
        try {

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
        */
    }
}
