<?php

namespace Acme\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acme\UserBundle\Entity\User;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{
    public function create(User $user, Thread $thread)
    {
        $em = $this->getEntityManager();
        
        $thread->setUser($user)
            ->setStatus(Thread::ITEM_UNLOCKED)
            ->setType(Thread::POST_NORMAL);
             
        $module = $thread->getModule();
        $module->setNumThreads($module->getNumThreads() + 1);
     
        $comment = new Comment();
        $comment->setUser($user)
                ->setThread($thread)
                ->setContent($thread->getContent())
                ->setVotes(0)
                ->setPostIndex(1);
                
        $thread->addComment($comment);
        
        $em->persist($module);
        $em->persist($thread);                    
        $em->persist($comment);
        $em->flush();                 
    }
}
