<?php

namespace Acme\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acme\UserBundle\Entity\User;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{
    public function create(User $user, Thread $thread)
    {
        $em = $this->getEntityManager();
        
        try {
            $em->getConnection()->beginTransaction(); // suspend auto-commit
            $thread->setUser($user);
            
            $em->persist($thread);
            $em->flush();
            
            $module = $thread->getModule();
            $module->setNumThreads($module->getNumThreads() + 1);
            $em->persist($module);
            
            $comment = new \Acme\BoardBundle\Entity\Comment();
            $comment->setUser($user)
                    ->setThread($thread)
                    ->setContent($thread->getContent())
                    ->setVotes(0)
                    ->setPostIndex(1);
                    
            $em->persist($comment);
            $em->flush();
            
            $em->getConnection()->commit();     
            
        } catch(\Exception $e) {
            $em->getConnection()->rollback();
            $em->close();
            throw $e;
        }    
        
    }
}
