comment_create:
    pattern:  /create
    defaults: { _controller: AcmeBoardBundle:Comment:create }

comment_vote:
    pattern:  /vote
    defaults: { _controller: AcmeBoardBundle:Asynchrony:vote }
    options:
        expose: true
    methods:  [POST]
        
comment_check:
    pattern:  /check
    defaults: { _controller: AcmeBoardBundle:Comment:check }
    options:
        expose: true
