thread:
    resource: "thread.yml"

comment:
    resource: "comment.yml"

#search:
#    pattern:  /search
#    defaults: { _controller: AcmeBoardBundle:Search:index }

module_index:
    pattern:  /
    defaults: { _controller: AcmeBoardBundle:Module:index }
