thread_index:
    pattern:  /{module_id}
    defaults: { _controller: AcmeBoardBundle:Thread:index }
    requirements:
        module_id:  \d+

thread_create:
    pattern:  /{module_id}/create
    defaults: { _controller: AcmeBoardBundle:Thread:create }
    requirements:
        module_id:  \d+

thread_view:
    pattern:  /thread/{id}
    defaults: { _controller: AcmeBoardBundle:Thread:view } 
    requirements:
        id:  \d+
     
thread_edit:
    pattern:  /thread/{id}/edit
    defaults: { _controller: AcmeBoardBundle:Thread:edit }
    requirements:
        id:  \d+
