parameters:
    
services:
    acme_user.change_password.form.factory:
        class: Acme\UserBundle\Form\Factory\FormFactory
        arguments:
            - @form.factory
            - change_password
            - @acme_user.change_password.form.type
            - []
            
    acme_user.change_password.form.type:
        class: Acme\UserBundle\Form\Type\ChangePasswordType
        tags: 
            - { name: form.type, alias: acme_user_change_password }

 
