_user_secured:
    resource: "@AcmeUserBundle/Controller/SecuredController.php"
    type:     annotation

change_password:
    pattern: /user/change_password
    defaults: { _controller: AcmeUserBundle:Secured:changePassword }

user_thread:
    pattern: /user/thread
    defaults: { _controller: AcmeUserBundle:Board:thread }

user_comment:
    pattern: /user/comment
    defaults: { _controller: AcmeUserBundle:Board:comment }

user_message:
    pattern: /user/message
    defaults: { _controller: AcmeUserBundle:Message:index }
    
user_send:
    pattern: /user/send
    defaults: { _controller: AcmeUserBundle:Message:send }
    requirements:
        id:  \d+
        
user_read:
    pattern: /user/read/{id}
    defaults: { _controller: AcmeUserBundle:Message:read }
    requirements:
        id:  \d+
        
user_exp:
    pattern: /user/exp
    defaults: { _controller: AcmeUserBundle:Message:exp }
    options:
        expose: true

locale:
    pattern: /locale
    defaults: { _controller: AcmeUserBundle:Locale:change }
