parameters:

services:
    signin_listener:
        class: 'Acme\UserBundle\EventListener\SigninListener'
        arguments: ['@security.context', '@doctrine.orm.entity_manager']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

