parameters:
        
services:    
    acme_user.user_manager:
        class: Acme\UserBundle\Doctrine\UserManager
        arguments:
            - @security.encoder_factory
            - @acme_user.util.canonicalizer
            - @acme_user.util.canonicalizer
            - @doctrine.orm.entity_manager
            - 'Acme\UserBundle\Entity\User'
    
    user_manager: "@acme_user.user_manager"
    
    acme_user_provider:
        class: Acme\UserBundle\Security\EmailUserProvider
        arguments: [@user_manager]
