parameters:
    acme_user.resetting.token_ttl: 3600
        
services:
    signin_listener:
        class: 'Acme\UserBundle\EventListener\SigninListener'
        arguments: ['@security.context', '@doctrine.orm.entity_manager']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
            
    acme_user.listener.resetting:
        class: 'Acme\UserBundle\EventListener\ResettingListener'
        arguments: ['@router', '%acme_user.resetting.token_ttl%']        
        tags:
            - { name: 'kernel.event_subscriber' }
    
    acme_user.user_manager:
        class: Acme\UserBundle\Doctrine\UserManager
        arguments:
            - @security.encoder_factory
            - @acme_user.util.canonicalizer
            - @acme_user.util.canonicalizer
            - @doctrine.orm.entity_manager
            - 'Acme\UserBundle\Entity\User'
    
    user_manager: "@acme_user.user_manager"
    
    acme_user_provider:
        class: Acme\UserBundle\Security\EmailUserProvider
        arguments: [@user_manager]
    
    acme_user.validator.initializer:
        class: Acme\UserBundle\Validator\Initializer
        arguments: [@user_manager]
        tags: 
            - { name: 'validator.initializer' }
        public: false
       
 

