# Acme/UserBundle/Resources/config/validation.yml
Acme\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 6
        password:
            - NotBlank: ~
            - Length:
                min: 8
        email:
            - NotBlank: ~
            - Email: ~
    getters:
        passwordLegal:
            - "True": { message: "The password cannot match your username" }

            
